version: '3'

x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  express_redis:
    image: "redis:6.0"
    ports:
      - "6379:6379"
    <<: *default-logging

  express_postgres:
    image: "postgres:13.0"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - express-postgres-data:/var/lib/postgresql/data
    <<: *default-logging

  # express_server:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_URL=postgres://postgres:postgres@express_postgres:5432/postgres
  #     - REDIS_HOST=express_redis
  #     - REDIS_PORT=6379
  #     - NODE_ENV=development
  #   depends_on:
  #     - express_redis
  #     - express_postgres
  #     - migrate
  #   volumes:
  #     - ./src:/app/src
  #     - ./package.json:/app/package.json
  #     - ./package-lock.json:/app/package-lock.json
  #     - ./tsconfig.json:/app/tsconfig.json

  migrate:
    build: .
    command: ["./run-migration.sh"]
    depends_on:
      - express_postgres
    environment:
      - DB_URL=postgres://postgres:postgres@express_postgres:5432/postgres
    <<: *default-logging

  judge_server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    depends_on:
      - judge_db
      - judge_redis
    environment:
      - POSTGRES_HOST=judge_db
      - REDIS_HOST=judge_redis
    env_file: judge0.conf
    <<: *default-logging

  judge_workers:
    image: judge0/judge0:1.13.0
    command: [ "./scripts/workers" ]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    depends_on:
      - judge_db
      - judge_redis
    environment:
      - POSTGRES_HOST=judge_db
      - REDIS_HOST=judge_redis
    env_file: judge0.conf
    <<: *default-logging

  judge_db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - judge-postgres-data:/var/lib/postgresql/data/
    <<: *default-logging

  judge_redis:
    image: redis:6.0
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
      ]
    env_file: judge0.conf
    volumes:
      - judge-redis-data:/data
    <<: *default-logging

volumes:
  express-postgres-data:
  judge-postgres-data:
  judge-redis-data:
