version: '3'
services:
  redis:
    image: "redis:6.0"
    
  postgres:
    image: "postgres:13.0"
    environment:
      - POSTGRES_PASSWORD=postgres
    
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgresql://postgres:postgres@localhost:5432/
      - REDIS_URL=redis://redis:6379

    depends_on:
      - redis
      - postgres
  